name: Create weekly release
on:
  schedule:
    - cron: '30 3 * * 3'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    strategy:
      fail-fast: false

    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls
          owner: mattmorz
          repo: lms-manlayag
          title: |-
            "chore: merge 'main-hotfix' into 'manlayag-v2.45'"
          body: "Automated weekly release"
          base: manlayag-v2.45
          head: main-hotfix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}